apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationset-pr-filter-plugin
  namespace: applicationset-pr-filter-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: applicationset-pr-filter-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: applicationset-pr-filter-plugin
    spec:
      containers:
        - name: api
          image: rminz/argocd-pr-filters:v0.13
          ports:
            - containerPort: 4355
              name: http
          volumeMounts:
            - mountPath: /var/run/argo/token
              name: token
              subPath: token
      volumes:
        - name: token
          secret:
            secretName: applicationset-pr-filter-plugin
