apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: applicationset-pr-filter-plugin
spec:
  selector:
    app.kubernetes.io/name: applicationset-pr-filter-plugin
  ports:
  - name: http
    port: 80
    targetPort: 4355
